apiVersion: v1
kind: Secret
metadata:
    name: server-credentials
type: Opaque
stringData:
    SERVER1_NAME: ENC[AES256_GCM,data:DuS6Yty8egXL,iv:U9u21tVLFOxs8q38yUvwkXaEO7ZXxyqcUmZCMi2yfHs=,tag:2cIktlE1ElKDGHOpkDENLg==,type:str]
    SERVER1_HOST: ENC[AES256_GCM,data:uTbuboSQFuAPsoiQxdBxGj3p7y9QZjk=,iv:4WjcTcYe7IJGMfOCce6wRiyCJu2EjCx0npM1LKcfmSY=,tag:CBSb4mPSUkft0UxGgHX4ng==,type:str]
    SERVER1_USERNAME: ENC[AES256_GCM,data:h3SPFlNxYFxeAlmotuJp,iv:tWPVikANWqF/D57nzr5X0OjOGuzhP3SiEYNYyd/b6LU=,tag:teBqrV+klzDBzHxG7QRZQw==,type:str]
    SERVER1_PASSWORD: ENC[AES256_GCM,data:TWZUyvd6WAiMFYQ=,iv:S1AnYFrzPMLROd4fuxaZBlCiFrAxTRzDNKXtrfgxlq4=,tag:vJ4yOdWoTkLSfCvCRq9qzA==,type:str]
    SERVER2_NAME: ENC[AES256_GCM,data:4pQGu902DpSf,iv:Y3O9rugSQ9Rfd/0H6aX7ETx6OqCVIj1QA0WpvcGSI3g=,tag:PfK8tMQDh7W8zV2JHx05NQ==,type:str]
    SERVER2_HOST: ENC[AES256_GCM,data:B0ZqmvirSdVJ+wSWmPKTuXo+f0zk0mA=,iv:BptEtzRUCx1guJtXiupdNaXmYwlBWH1+rF71hKoOARQ=,tag:dt5DHmicNZ47/a4OaEo+Qg==,type:str]
    SERVER2_USERNAME: ENC[AES256_GCM,data:1nvugvHrYjnPzscmh+kF,iv:fKDCf+IgvmPVidJZS54NbFRvJZTTww5bAb/ydE3xz6c=,tag:tl8MdEPLnpajTWTelbM1bw==,type:str]
    SERVER2_PASSWORD: ENC[AES256_GCM,data:C7L53vxpQQ5xKaM=,iv:6IY9P56t9ZNAUdo6x73R+J9hkhAg07N5xQLTgHUXsuI=,tag:OEGe0TGjxOQLsXVDZtAdeA==,type:str]
    FEED1_NAME: ENC[AES256_GCM,data:DLM/L7bntg==,iv:vU5UUbgrEDWAoXRqv5zAj8NnuFiTX7tHi2boZsP7rqE=,tag:KTIkwwJ0k2pWabaXseZquQ==,type:str]
    FEED1_URL: ENC[AES256_GCM,data:aEoq28gM1YjMvs4aWbo5HwT4kSWyRTT0miyv5+OuBGTmd1EXn4q4kx2mr0KVMKDs5uCHl6LicG16QK1FwbtWCMIvnSSWfLgeWbSD+TQgiIb7wHJJMNcrAb8=,iv:X7+imu3Y7CQvsjC0oJNVisICPnkyBBmwzlhdjlD1xmY=,tag:FsyWAKBzQJHm/6BXelj2cg==,type:str]
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbjRsbmxEdTdkMUZGalJj
            Y1hQSTREckF1S0ozRWRsWFNjN2g2UUsrdlFBCkFwZWVocGVoNlRyejBnTGc3eEtr
            OGJLSGpmenFpQi9DWnpPbXZRVWM3UmMKLS0tIDJsczhSemkrMmpEVUlQaGpDdUVi
            SzhtNFhjcGlVMUJ4WHZ1eEMxTCs2OGcKaZVhetGvxkdOJCYrdihVY+ORIAz+OpT3
            XaX9NaakezD0IcYXyDemPHpQjQ05eJ3fcvK1N9UiUZRY9pIb/9anLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:49:05Z"
    mac: ENC[AES256_GCM,data:H+qFvcW0cL8BmBRJasyuXFigp9NaeH09DUlVE84Vyu2HBtTj3PESqBbSCy0KsWRIxHfbeDQr0lLakHglAjS86IGo+O0qLoeNtoa2H2ejp4nlatKY12Y8Db1IXC/VI8cjSP5CLpo3OEsR/HEmOj7h5y/yCPkGEZs9hQlMi2ZzwWo=,iv:QBOox+CMbRQJ8zROveec27gg6Tv7gaIgDzN9zc8q4NM=,tag:mssDxiYit4oVMXqaGTUnfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
