---
apiVersion: v1
kind: Service
metadata:
  name: nzbget
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: nzbget
  labels:
    external-dns: "true"
spec:
  parentRefs:
    - name: services
      namespace: infra
      sectionName: main
  # replaced by kustomize
  hostnames: []
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: nzbget
          port: 80
