apiVersion: v1
kind: Secret
metadata:
    name: telegram-bot
    namespace: observability
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:58gO98Q9oeBwa5vlAl7vIVlQsDf0PcWumx20h/j1KtFA9V9DPWAjcypmxFMofQ==,iv:6nDtZxXhRtFr1lAdcHCbtuvjgpknVYOUwRxWh4Atpe4=,tag:Gy2kYFmPjImxRH7xaYnq1Q==,type:str]
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTnArU0o0RnMyU0lOVWcr
            WUd5M3MxemRXazZJL2tkdHM3UnNhRkZmV1g0Cjk4d2phNjZuMFdjcUFOY0tZSzN3
            RDhEdnlIZVBaQ0JqcGkwU1FZbDIyeGcKLS0tIGUwemU4Sk5LeEpOZEFHUHc3eWUx
            ZUlrWUNpY1dxaUlDcW5rRGxGL0h1SW8KO7Bh30VHFzAIOerC/SBYRK+glDLUxkTR
            1qmBhufRo5+OY9HJ92Z8VkghK2BRf/xtDFSSPy6RzZKlV2thFhIVSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:BAuoCz8UnMs8QM1saecTM7CMdjBBmVBN6ONK4QeelkRkmuzuMjJVm6Rxh+/Wja+i52nbUMX00/p0iif4FcTtvNohfBMZkbwDyLx2+ifTIqIE+gkXT7pxfF+GTegCyQQXBy23ENb9ypwG/+l4l83CHCYf21GfWpcyXV0POGMN1qQ=,iv:rMloZUvA40E4IZoEUrFNrCkgZ2xhF9frqPODr9TdeKQ=,tag:gDE830NAxqSoeAkU70Z3Tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: watchdog-webhook
    namespace: observability
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:ypxOu/TDmI9CTLoPBW1ui530Q064zGnvB+kPDwPe49zHve0v5LyGj0nCw7eC/4Z1Rechsu7/RKQ=,iv:Rqk36kU0AAnATAltU7uT2lz+WobmpoFrz5Dx6Q7WVNA=,tag:jR+p+yPbVV58Q7GtWUl6FA==,type:str]
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTnArU0o0RnMyU0lOVWcr
            WUd5M3MxemRXazZJL2tkdHM3UnNhRkZmV1g0Cjk4d2phNjZuMFdjcUFOY0tZSzN3
            RDhEdnlIZVBaQ0JqcGkwU1FZbDIyeGcKLS0tIGUwemU4Sk5LeEpOZEFHUHc3eWUx
            ZUlrWUNpY1dxaUlDcW5rRGxGL0h1SW8KO7Bh30VHFzAIOerC/SBYRK+glDLUxkTR
            1qmBhufRo5+OY9HJ92Z8VkghK2BRf/xtDFSSPy6RzZKlV2thFhIVSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:BAuoCz8UnMs8QM1saecTM7CMdjBBmVBN6ONK4QeelkRkmuzuMjJVm6Rxh+/Wja+i52nbUMX00/p0iif4FcTtvNohfBMZkbwDyLx2+ifTIqIE+gkXT7pxfF+GTegCyQQXBy23ENb9ypwG/+l4l83CHCYf21GfWpcyXV0POGMN1qQ=,iv:rMloZUvA40E4IZoEUrFNrCkgZ2xhF9frqPODr9TdeKQ=,tag:gDE830NAxqSoeAkU70Z3Tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
