write-talosconfig outfile:
    terraform output -raw talosconfig > {{ outfile }}

write-kubeconfig outfile:
    terraform output -raw kubeconfig > {{ outfile }}

write-secrets-yaml outfile:
    terraform output -json machine_secrets | yq --input-format json --output-format yaml . > {{ outfile }}

_get-id:
    #!/usr/bin/env bash
    curl --silent -X POST https://factory.talos.dev/schematics --data-binary @- << EOF | jq -r .id
      customization:
        extraKernelArgs:
          - sysctl.net.ipv6.conf.default.stable_secret=`echo 'var.stable_secret' | terraform console | tr -d '"'`
    EOF

get-secureboot-iso version:
  wget "https://factory.talos.dev/image/`just _get-id`/{{ version }}/metal-amd64-secureboot.iso"
