apiVersion: v1
kind: Namespace
metadata:
    name: cert-manager
    labels:
        pod-security.kubernetes.io/enforce: restricted
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK3VpVDd4TVJOZWw4L0hN
            UVR0RXZZaWVjcVNKTVVWU3FjM1VxT2JGT1FNCk5zT0dqR0p6bDhJSFhCaWd1NmVH
            cG10cWlKMytleHU4RVZsNCt1Y2tvaUEKLS0tIEx0cEFGditNbkxNY1czYkFpdXJm
            a2FWYVcyemN6aEd5bmdialkrT0h0YVUKFT8j8pxyK/JyS/dsEdbupUTk+7D/kuT4
            A5B47MMc9wwl9W7jB+v3mV9YfFMIcVd8dg6Jnwt8dudXTaB61UgDxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:PCoPmy+3gINAloG8ZcxBDDNjBzxkJNuMvVjBitrawVHQx0GWY+RjWxvhLIE9QacefQJBZzfS3w44lv8sXgYxgD1dfpUmd76M/12mns/BhcOWhdhnP4905kmKhSpS6BM5+bh0ddIW72MvuMqDjOwdB7rjRhboKU19YJN4c5fcMuM=,iv:OjYU7+NjiRGlu1BGxr62mjWlmUjSXHsq4Xoimc7FnXo=,tag:HaEmWwsKHfURcQfkT1jdeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: jetstack
    namespace: cert-manager
spec:
    interval: 10m0s
    url: https://charts.jetstack.io
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK3VpVDd4TVJOZWw4L0hN
            UVR0RXZZaWVjcVNKTVVWU3FjM1VxT2JGT1FNCk5zT0dqR0p6bDhJSFhCaWd1NmVH
            cG10cWlKMytleHU4RVZsNCt1Y2tvaUEKLS0tIEx0cEFGditNbkxNY1czYkFpdXJm
            a2FWYVcyemN6aEd5bmdialkrT0h0YVUKFT8j8pxyK/JyS/dsEdbupUTk+7D/kuT4
            A5B47MMc9wwl9W7jB+v3mV9YfFMIcVd8dg6Jnwt8dudXTaB61UgDxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:PCoPmy+3gINAloG8ZcxBDDNjBzxkJNuMvVjBitrawVHQx0GWY+RjWxvhLIE9QacefQJBZzfS3w44lv8sXgYxgD1dfpUmd76M/12mns/BhcOWhdhnP4905kmKhSpS6BM5+bh0ddIW72MvuMqDjOwdB7rjRhboKU19YJN4c5fcMuM=,iv:OjYU7+NjiRGlu1BGxr62mjWlmUjSXHsq4Xoimc7FnXo=,tag:HaEmWwsKHfURcQfkT1jdeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: cert-manager
spec:
    install:
        crds: Skip
    upgrade:
        crds: Skip
    interval: 10m0s
    dependsOn:
        - name: envoy-gateway
          namespace: envoy-gateway-system
    chart:
        spec:
            chart: cert-manager
            sourceRef:
                kind: HelmRepository
                name: jetstack
            version: v1.20.2
    values:
        global:
            hostUsers: true
        installCRDs: true
        config:
            enableGatewayAPI: true
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK3VpVDd4TVJOZWw4L0hN
            UVR0RXZZaWVjcVNKTVVWU3FjM1VxT2JGT1FNCk5zT0dqR0p6bDhJSFhCaWd1NmVH
            cG10cWlKMytleHU4RVZsNCt1Y2tvaUEKLS0tIEx0cEFGditNbkxNY1czYkFpdXJm
            a2FWYVcyemN6aEd5bmdialkrT0h0YVUKFT8j8pxyK/JyS/dsEdbupUTk+7D/kuT4
            A5B47MMc9wwl9W7jB+v3mV9YfFMIcVd8dg6Jnwt8dudXTaB61UgDxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:PCoPmy+3gINAloG8ZcxBDDNjBzxkJNuMvVjBitrawVHQx0GWY+RjWxvhLIE9QacefQJBZzfS3w44lv8sXgYxgD1dfpUmd76M/12mns/BhcOWhdhnP4905kmKhSpS6BM5+bh0ddIW72MvuMqDjOwdB7rjRhboKU19YJN4c5fcMuM=,iv:OjYU7+NjiRGlu1BGxr62mjWlmUjSXHsq4Xoimc7FnXo=,tag:HaEmWwsKHfURcQfkT1jdeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: cert-manager
stringData:
    token: ENC[AES256_GCM,data:2Yr0AS29lNstsguvECH+77+VXEoaZpeYw59NMq4hJdUs6GnlgieiRw==,iv:c0trlBIw7HgE+HAKXyObhFH5pfbnSmWrs0DPl54mCS4=,tag:mt3tN/GJcKq9OanL4OhUWw==,type:str]
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK3VpVDd4TVJOZWw4L0hN
            UVR0RXZZaWVjcVNKTVVWU3FjM1VxT2JGT1FNCk5zT0dqR0p6bDhJSFhCaWd1NmVH
            cG10cWlKMytleHU4RVZsNCt1Y2tvaUEKLS0tIEx0cEFGditNbkxNY1czYkFpdXJm
            a2FWYVcyemN6aEd5bmdialkrT0h0YVUKFT8j8pxyK/JyS/dsEdbupUTk+7D/kuT4
            A5B47MMc9wwl9W7jB+v3mV9YfFMIcVd8dg6Jnwt8dudXTaB61UgDxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:PCoPmy+3gINAloG8ZcxBDDNjBzxkJNuMvVjBitrawVHQx0GWY+RjWxvhLIE9QacefQJBZzfS3w44lv8sXgYxgD1dfpUmd76M/12mns/BhcOWhdhnP4905kmKhSpS6BM5+bh0ddIW72MvuMqDjOwdB7rjRhboKU19YJN4c5fcMuM=,iv:OjYU7+NjiRGlu1BGxr62mjWlmUjSXHsq4Xoimc7FnXo=,tag:HaEmWwsKHfURcQfkT1jdeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
