apiVersion: v1
kind: Namespace
metadata:
    name: external-dns
    labels:
        pod-security.kubernetes.io/enforce: restricted
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS2NyYnJmTmJONFMwUlhX
            SmliMUM2Y0tiaHBsV2ZhQXRZV1pLckJGZEQwCkhPZ29Ed2s1QUxlVU8rdWxiVjVF
            eEVZMi9FM216MmRuTTkxYVR0VHRGMjAKLS0tIERJQy8vRVdmczZJVXB5WHlIRjRo
            SnI0NlNRY2FGdUIzL1BGMm1GMndVQjQKO4ApvR/ccqw8hmp8p6vEFz90abZFfZ6E
            J92Jg5NDHxehc3YCOxI0Hrlf8wciNS3CBgX8KSjpnsWbpv6AN+NVMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:2l8XZtUzFqhdSNoUFFjo8BNXgbCuxxLAM5sZtrGTxU+tEiCqrHlI350Koy68gRSSCfcvfWg15uCvSwtLxI6IGQgAbjYsIIAF8Qx1/BUT6FoOjfS3AuUfMHbNlIPFdFaoEaXtiYK+PtQ6KWwOJHMBp0VDzGM+IKWupQvwbQBaTDk=,iv:A7HyyGRq1t4qyWS3RVuaFXscGTMN7XE7lrQ5kFn0Gl8=,tag:K5n48ME/F6sRc6Oeu7j5PA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: external-dns
    namespace: external-dns
spec:
    interval: 10m0s
    url: https://kubernetes-sigs.github.io/external-dns
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS2NyYnJmTmJONFMwUlhX
            SmliMUM2Y0tiaHBsV2ZhQXRZV1pLckJGZEQwCkhPZ29Ed2s1QUxlVU8rdWxiVjVF
            eEVZMi9FM216MmRuTTkxYVR0VHRGMjAKLS0tIERJQy8vRVdmczZJVXB5WHlIRjRo
            SnI0NlNRY2FGdUIzL1BGMm1GMndVQjQKO4ApvR/ccqw8hmp8p6vEFz90abZFfZ6E
            J92Jg5NDHxehc3YCOxI0Hrlf8wciNS3CBgX8KSjpnsWbpv6AN+NVMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:2l8XZtUzFqhdSNoUFFjo8BNXgbCuxxLAM5sZtrGTxU+tEiCqrHlI350Koy68gRSSCfcvfWg15uCvSwtLxI6IGQgAbjYsIIAF8Qx1/BUT6FoOjfS3AuUfMHbNlIPFdFaoEaXtiYK+PtQ6KWwOJHMBp0VDzGM+IKWupQvwbQBaTDk=,iv:A7HyyGRq1t4qyWS3RVuaFXscGTMN7XE7lrQ5kFn0Gl8=,tag:K5n48ME/F6sRc6Oeu7j5PA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-dns
    namespace: external-dns
spec:
    install:
        crds: CreateReplace
    upgrade:
        crds: CreateReplace
    interval: 10m0s
    targetNamespace: external-dns
    chart:
        spec:
            chart: external-dns
            sourceRef:
                kind: HelmRepository
                name: external-dns
            version: 1.21.1
    values:
        policy: sync
        txtOwnerId: k8rn
        sources:
            - gateway-httproute
            - gateway-tlsroute
            - gateway-tcproute
            - service
        provider:
            name: cloudflare
        extraArgs:
            label-filter: external-dns==true
            managed-record-types:
                - A
                - AAAA
        env:
            - name: CF_API_TOKEN
              value: file:/cloudflare/token
        secretConfiguration:
            enabled: true
            mountPath: /cloudflare
            data:
                token: ENC[AES256_GCM,data:ZBb19h9jqhPB/eEO9aI+VsYWW3GiVdGyT1AcwHQAvSs2IbZH8yi0RA==,iv:U0jFxKYfATMkjHIIN+y9p6cWPb2t3dofzn2BTd1709s=,tag:3/Mklu7RxYwh5y8I1uznWw==,type:str]
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS2NyYnJmTmJONFMwUlhX
            SmliMUM2Y0tiaHBsV2ZhQXRZV1pLckJGZEQwCkhPZ29Ed2s1QUxlVU8rdWxiVjVF
            eEVZMi9FM216MmRuTTkxYVR0VHRGMjAKLS0tIERJQy8vRVdmczZJVXB5WHlIRjRo
            SnI0NlNRY2FGdUIzL1BGMm1GMndVQjQKO4ApvR/ccqw8hmp8p6vEFz90abZFfZ6E
            J92Jg5NDHxehc3YCOxI0Hrlf8wciNS3CBgX8KSjpnsWbpv6AN+NVMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:2l8XZtUzFqhdSNoUFFjo8BNXgbCuxxLAM5sZtrGTxU+tEiCqrHlI350Koy68gRSSCfcvfWg15uCvSwtLxI6IGQgAbjYsIIAF8Qx1/BUT6FoOjfS3AuUfMHbNlIPFdFaoEaXtiYK+PtQ6KWwOJHMBp0VDzGM+IKWupQvwbQBaTDk=,iv:A7HyyGRq1t4qyWS3RVuaFXscGTMN7XE7lrQ5kFn0Gl8=,tag:K5n48ME/F6sRc6Oeu7j5PA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
