---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alerts
  namespace: flux-system
spec:
  groups:
    - name: flux
      rules:
        - alert: FluxResourceNotReady
          annotations:
            description: "{{ $labels.customresource_kind }} {{ $labels.namespace }}/{{ $labels.name }} isn't ready!"
            summary: "A Flux resource isn't ready"
          # OCI HelmRepository doesn't report readiness
          expr: |-
            (
              gotk_resource_info{ready!="True",url!~"oci://.*"} != 0
            )
          for: 10m
          labels:
            severity: warning
