apiVersion: v1
kind: Secret
metadata:
    name: admin-token
stringData:
    #ENC[AES256_GCM,data:dHzXV2zupuYs/06CgPHvsX6++msqY7i+VQo8tAENoBxJ7rD2jcQeWg==,iv:hwZuicz5K8zWhIQmKlK7BzEGZiYgAzaMHgSwCw1ikk0=,tag:ZR6FrJeALTezCgLUNK3WYA==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:DwcWWQ/L8ub3vE3A8Krc1Rhrf13vWbqe,iv:FwxK355v600fQjZKG81wweO1QeXsW8vzFvsZylZ2eD4=,tag:SEK4c5WXbCYDrof03TdFlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mc6573986ak84qcs9slsel3rahaw8gjseh5f085gyr6zhz6yuu7qqhluwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWGZwM0lxWDYrb1RLMmFQ
            cmQ5OG1yVmM4RDg5TlQzc1NVMzZZa1J0b1NJClY2VzFQN1NnaWJlcmFSUGtTd2NY
            UWliRitYak1kaytaczFJUnR3RDcyUGMKLS0tIENXQmVWM0p3UjFUQ2s5Ty9vSklu
            dlg0WHZNU3lyeEljaFJET2Eva3dXNmsKkghJxuuU+6ozF06cP0VGPM4tl/JJsSkp
            tOTfxMr5E4DwUBxVZHckBhLN5K23544GxbdiawF+dP/woK+frVHmzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T20:07:25Z"
    mac: ENC[AES256_GCM,data:1YF9qLD5dJnt6HyWDU7QoOl4eBZYg3+hVGCFFZExtlWDza/DYudNO0GVoYBSn/jg8IWApyKODC6AO10yDg5fftNAeEybsmdOCT9Hhc0pprO+HxJunxAy/I3moHtI8uY7TlEK+fZ+D9q0pT9eJyS5k6JQMEWFhESBCZ50rK3jLzM=,iv:uh9J9nteLP7ttzLgEmMfmXhN7SxbbLH/IDIbMEBbgSE=,tag:Kq+gIRI/7jsqv8u7H24dVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
