---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: vaultwarden
data:
  ROCKET_PORT: "8080"
  DOMAIN: "https://passwords.${services_hostname_suffix}"
  SIGNUPS_ALLOWED: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vaultwarden
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: vaultwarden
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          image: docker.io/vaultwarden/server:1.32.0
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: admin-token
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
