apiVersion: v1
kind: Secret
metadata:
    name: oidc
stringData:
    SSO_ENABLED: ENC[AES256_GCM,data:boGA9g==,iv:UT9UlQOffwSRd4B1Zoir7hSxIREwczuTLWtfJzjhEmo=,tag:GCztu68qbcij+XrwbQMsVg==,type:str]
    SSO_ONLY: ENC[AES256_GCM,data:mntblQ==,iv:meEkZaocLtdcZhk2mr2/PQwgan+1pN6i9OCxy2wmXlo=,tag:Ub7TMBrxPdlyl41amGcPLg==,type:str]
    SSO_SIGNUPS_MATCH_EMAIL: ENC[AES256_GCM,data:PbZwGQ==,iv:eMFK4vKTI+JxlRsrgoXtPDzjLB0bDLMdbWhEPnf6604=,tag:F3gS2gMsxT64YAIjBcVJSg==,type:str]
    SSO_AUTHORITY: ENC[AES256_GCM,data:qJcdAAKtnm33fTnasRln9ow3/+XlWFwUAdd0,iv:sbWPsSwo4TK1A5bRg00fVABqx+WP35S7eGeNby6j0vg=,tag:GrcWKI4fzcVY3+UJytK6Zg==,type:str]
    SSO_PKCE: ENC[AES256_GCM,data:yA+tYA==,iv:mpYlaOfiw0UxGpWY7z9x/19QiwgFksSE5T7xk+8Y20Q=,tag:62tdfjtID70QxtpUT/msDg==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:khC5LW1zYS6kMu4X5cvM4Lz6A3Uzh1JbDF52kJJMxVnr86Fw,iv:dENG7eUT8HrrOBr0aTvbMQc2auG9qoqM8OUqjcwQj54=,tag:BmT3BhRPSGfG9OicGZofuw==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:QN9gLGSaUyc6bmZzQd2Ytq/QW09h+5kkvsb8eC4pADs=,iv:Tkb9k1wCaUQ4xY64utspCEFiVpUNCjSDAyaXD3vALTg=,tag:2DYESmRZCukEQSu3QP/oCA==,type:str]
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aUZVNDEvZ0tLMjVRcHVZ
            Z0hGK0k2UDYyYmpYNmVua2lCdjlXZVBlbWxFCjFWMVNsTGpWMjV5NXJnUmhXcGgr
            MzgxZjBJQUlPU0lUaU5GU3JTcnNpY1UKLS0tIEJyNURIWC9MeUpsbExkSWFBZVRZ
            NXpGYkFNOWlhNjM3UG54aE4yMDR2cUUK4ZVrlR88DYs7U3KUFKGbLpOwoUjg+m7A
            AiaRMcBHEMPkCZ6WWpJJv3hSZ+JFHU+Qj1QX/8W7RLO7RRvR52Cdkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:48:20Z"
    mac: ENC[AES256_GCM,data:OGFI3F2OKDL8YDjWX/fZU2T37nX9BXzjtCK4c4HvbwJRd20HYU7y2JS9eSaHON54nYeYSUxt4AVaAlwbHDFBzSjGaanobd/Dl+tee+DQFGWirmgdLJq5UvBn/z7YgKIiYHzCMYSgZfR8RvIIwGb3IgF8kMEibnz33UUutSDkSTw=,iv:llQAdJcdFrxuDFoqk382SQnP5MtYYQlOG+zNodOSpnE=,tag:rI/uVnJFe5C/evMhA60BiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: admin-token
stringData:
    #ENC[AES256_GCM,data:nD8B1XQ3MLmwOFaLOEMRzqrHY2JtOv/rDcPSdRMZ2jCugwLP/141pw==,iv:hwZuicz5K8zWhIQmKlK7BzEGZiYgAzaMHgSwCw1ikk0=,tag:vGAGnIYxQl2mccyIRna2XQ==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:fHyPZZG5uBjbbD6zXRrqYMaxrizxCo+M,iv:FwxK355v600fQjZKG81wweO1QeXsW8vzFvsZylZ2eD4=,tag:qAYtcO/cjL0FtNGKjNpSFg==,type:str]
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aUZVNDEvZ0tLMjVRcHVZ
            Z0hGK0k2UDYyYmpYNmVua2lCdjlXZVBlbWxFCjFWMVNsTGpWMjV5NXJnUmhXcGgr
            MzgxZjBJQUlPU0lUaU5GU3JTcnNpY1UKLS0tIEJyNURIWC9MeUpsbExkSWFBZVRZ
            NXpGYkFNOWlhNjM3UG54aE4yMDR2cUUK4ZVrlR88DYs7U3KUFKGbLpOwoUjg+m7A
            AiaRMcBHEMPkCZ6WWpJJv3hSZ+JFHU+Qj1QX/8W7RLO7RRvR52Cdkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:48:20Z"
    mac: ENC[AES256_GCM,data:OGFI3F2OKDL8YDjWX/fZU2T37nX9BXzjtCK4c4HvbwJRd20HYU7y2JS9eSaHON54nYeYSUxt4AVaAlwbHDFBzSjGaanobd/Dl+tee+DQFGWirmgdLJq5UvBn/z7YgKIiYHzCMYSgZfR8RvIIwGb3IgF8kMEibnz33UUutSDkSTw=,iv:llQAdJcdFrxuDFoqk382SQnP5MtYYQlOG+zNodOSpnE=,tag:rI/uVnJFe5C/evMhA60BiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
