---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-docs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: docs
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: data
    volumeHandle: docs
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8rn-core
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-zfs-data
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs
spec:
  volumeName: paperless-docs
  storageClassName: openebs-zfs-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: docs-backup
spec:
  sourcePVC: docs
  trigger:
    schedule: "0 */1 * * *"
  restic:
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    repository: restic-config-zfs-docs
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Snapshot
    storageClassName: openebs-zfs-data-delete
    cacheStorageClassName: openebs-single-replica-delete
    cacheCapacity: 5Gi
    volumeSnapshotClassName: openebs-zfs-localpv-delete
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: docs-backup-local
spec:
  sourcePVC: docs
  trigger:
    schedule: "30 */12 * * *"
  restic:
    pruneIntervalDays: 14
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    repository: restic-config-zfs-docs-local
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Snapshot
    storageClassName: openebs-zfs-data-delete
    cacheStorageClassName: openebs-single-replica-delete
    cacheCapacity: 5Gi
    volumeSnapshotClassName: openebs-zfs-localpv-delete
    moverVolumes:
      - mountPath: local-backups
        volumeSource:
          persistentVolumeClaim:
            claimName: docs-local-backup
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-docs-local-backup
spec:
  capacity:
    storage: 1Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: docs-local-backup
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/mnt/backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8rn-core
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docs-local-backup
spec:
  volumeName: paperless-docs-local-backup
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
