---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-media
spec:
  claimRef:
    name: media
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /data/docs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  volumeName: paperless-media
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
