apiVersion: v1
kind: Namespace
metadata:
  name: paperless
  labels:
    gateway.infra.services/allow-routes: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:2.19.0
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          env:
            - name: PAPERLESS_APP_TITLE
              value: Docs
            - name: PAPERLESS_PORT
              value: "8000"
            - name: PAPERLESS_TIME_ZONE
              value: Europe/Berlin
            - name: PAPERLESS_APPS
              value: allauth.socialaccount.providers.openid_connect
            - name: S6_READ_ONLY_ROOT
              value: "1"
            - name: S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES
              value: "1"
          envFrom:
            - secretRef:
                name: oidc-client
          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
            - name: media
              mountPath: /usr/src/paperless/media
            - name: paperless-scratch
              mountPath: /run
              subPath: run
            - name: paperless-scratch
              mountPath: /tmp
              subPath: tmp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
        - name: redis
          image: docker.io/valkey/valkey:9.0
          args:
            - valkey-server
            - /etc/redis/redis.conf
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/redis
              name: redis-config
            - mountPath: /data
              name: redis-data
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
        - name: redis-config
          configMap:
            name: redis
            items:
              - key: redis.conf
                path: redis.conf
        - name: paperless-scratch
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
data:
  redis.conf: |
    bind 127.0.0.1
