apiVersion: v1
kind: Namespace
metadata:
  name: paperless
  labels:
    gateway.infra.services/allow-routes: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      containers:
        - name: paperless
          image: ghcr.io/paperless-ngx/paperless-ngx:2.12.1
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          env:
            - name: PAPERLESS_URL
              value: https://docs.${services_hostname_suffix}
            - name: PAPERLESS_APP_TITLE
              value: Docs
            - name: PAPERLESS_PORT
              value: "8000"
            - name: PAPERLESS_TIME_ZONE
              value: Europe/Berlin
          volumeMounts:
            - name: data
              mountPath: /usr/src/paperless/data
            - name: media
              mountPath: /usr/src/paperless/media
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
        - name: redis
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          image: docker.io/redis:7.4
          args:
            - redis-server
            - /etc/redis/redis.conf
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/redis
              name: redis-config
            - mountPath: /data
              name: redis-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
        - name: redis-config
          configMap:
            name: redis
            items:
              - key: redis.conf
                path: redis.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: paperless
data:
  redis.conf: |
    bind 127.0.0.1
