---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-data
type: Opaque
stringData:
    RESTIC_PASSWORD: ${RESTIC_PASSWORD}
    RESTIC_REPOSITORY: ${RESTIC_REPOSITORY_BASE}/paperless/data
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-zfs-docs
type: Opaque
stringData:
    RESTIC_PASSWORD: ${RESTIC_PASSWORD}
    RESTIC_REPOSITORY: ${RESTIC_REPOSITORY_ZFS_DATA_BASE}/docs
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_ZFS_DATA}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_ZFS_DATA}
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-config-zfs-docs-local
type: Opaque
stringData:
    RESTIC_PASSWORD: "-"
    RESTIC_REPOSITORY: local:/mnt/local-backups/docs
