---
apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
spec:
  selector:
    app.kubernetes.io/name: paperless
  ports:
    - port: 80
      targetPort: http
      name: http
      appProtocol: http
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: docs
  namespace: paperless
  labels:
    external-dns: "true"
spec:
  parentRefs:
    - name: services
      namespace: infra
      sectionName: main
  hostnames:
    - docs.${services_hostname_suffix}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: paperless
          port: 80
