---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cilium-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cilium-install
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-install
  namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cilium-install-v1-16-1
  namespace: kube-system
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: cilium-install-v1-16-1
    spec:
      restartPolicy: OnFailure
      tolerations:
        - operator: Exists
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - effect: PreferNoSchedule
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoExecute
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: PreferNoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      serviceAccount: cilium-install
      serviceAccountName: cilium-install
      hostNetwork: true
      containers:
        - name: cilium-install
          image: quay.io/cilium/cilium-cli-ci:latest
          env:
            - name: KUBERNETES_SERVICE_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: KUBERNETES_SERVICE_PORT
              value: "6443"
          command:
            - cilium
            - install
            - --version
            - v1.16.1
            - --set=ipam.mode=kubernetes
            - --set=ipv6.enabled=true
            - --set=kubeProxyReplacement=false
            - --set=envoy.baseID=4244 # random number, needed to avoid conflicts with other Envoy instances
            # don't actually enable hubble for now
            # - --set=hubble.relay.enabled=true
            # - --set=hubble.ui.enabled=true
            - --set-string=securityContext.capabilities.ciliumAgent={CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}
            - --set-string=securityContext.capabilities.cleanCiliumState={NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}
            - --set=cgroup.autoMount.enabled=false
            - --set=cgroup.hostRoot=/sys/fs/cgroup
            # Host networking use kube prism to contact k8s API
            - --set=k8sServiceHost=localhost
            - --set=k8sServicePort=7445
