apiVersion: v1alpha1
kind: ImageVerificationConfig
rules:
  - image: registry.k8s.io/*
    keyless:
      issuer: https://accounts.google.com
      subject: krel-trust@k8s-releng-prod.iam.gserviceaccount.com
  - image: ghcr.io/siderolabs/talos-cloud-controller-manager
    keyless:
      issuer: https://token.actions.githubusercontent.com
      subjectRegex: '^https://github\.com/siderolabs/talos-cloud-controller-manager/.*$'
  - image: ghcr.io/siderolabs/*
    keyless:
      issuer: https://accounts.google.com
      subjectRegex: '(@siderolabs\.com$|^releasemgr-svc@talos-production\.iam\.gserviceaccount\.com$)'
  - image: factory.talos.dev/*
    keyless:
      issuer: https://accounts.google.com
      subject: image-factory-signing@talos-production.iam.gserviceaccount.com
  - image: ghcr.io/fluxcd/*
    keyless:
      issuer: https://token.actions.githubusercontent.com
      subjectRegex: '^https://github\.com/fluxcd/.*$'
  - image: ghcr.io/michaelbeaumont/talos-kms-seals
    keyless:
      issuer: https://token.actions.githubusercontent.com
      subjectRegex: '^https://github\.com/michaelbeaumont/talos-kms-seals/.*$'
  - image: ghcr.io/michaelbeaumont/*
    keyless:
      issuer: https://token.actions.githubusercontent.com
      subjectRegex: '^https://github\.com/michaelbeaumont/k8rn/.*$'
  - image: quay.io/cilium/*
    keyless:
      issuer: https://token.actions.githubusercontent.com
      subjectRegex: '^https://github\.com/cilium/cilium/.*$'
