cluster:
  apiServer:
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1alpha1
          defaults:
            audit: restricted
            audit-version: latest
            enforce: privileged
            enforce-version: latest
            warn: restricted
            warn-version: latest
          # don't add any exemptions
          kind: PodSecurityConfiguration
