apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oidc-issuer-config-sync
labels:
  - includeTemplates: true
    includeSelectors: true
    pairs:
      app.kubernetes.io/name: oidc-issuer-config-sync-push
resources:
  - cronjob.yaml
  - secret.yaml
