apiVersion: v1
kind: Secret
metadata:
    name: dht-private-key
stringData:
    dht-private-key: ENC[AES256_GCM,data:BWaYkxl6i5djYZ3lQv1Faeiiiwsbs/kxOpanW0R313hMYIYenpcq3EBJcDBg8t/Dk2PaVsOkM2Ck4ELYeVcP5A==,iv:X5XP6EV6isOQsWNsxRW6rS8tC1lrT8wxpvAJlB9XU7M=,tag:BKVi14qdhxd/RTP2ha/Dxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMUpmNGVTV3JLekpYSHBM
            RUR1emJKNGpGZytzTkZnaGlUdzZRVnpTdTBVCmJGQXNwbjJyMmdZMk1EMTFpNXZk
            OVo0azJrQW85eUVhQzI2cmx2QXRONFEKLS0tIGtQSVIzdllmejlVWm54ekhRbXVH
            bzdoUnREcVpkQ3hjeFFCUEhSeHdlOEEKmCfHQRhf/bM7NORzHTq+1I92BWEBIXXm
            xinB0sJs/Jmyeo+EAkWDRPsqexkRuJTzE4+anCKTIn7fEw85Et8Ztw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T18:48:44Z"
    mac: ENC[AES256_GCM,data:6CET9IswTTXvLYdnlEviYZXZEG1OyIUSxvtwErRCpyb7PufJnVfR+Cjma+3bj2SlmlY0INBtlbSF+eJdL+qfpoXyKU8r4k1SUKlBpLAcDTPaUn3zhK4Uab82Z9XwE0441Ixntw48T433YD2EsLTVgF7YXBwe5iEqQu5pkUZYnxo=,iv:i5/WW+GHgTwUeqEi0o99YSon2vZMtgXVe2/578DOsFg=,tag:ZTt/iFhj8Ag448C80UjBYg==,type:str]
    version: 3.13.2
