apiVersion: v1
kind: Secret
metadata:
    name: dht-private-key
stringData:
    dht-private-key: ENC[AES256_GCM,data:BWaYkxl6i5djYZ3lQv1Faeiiiwsbs/kxOpanW0R313hMYIYenpcq3EBJcDBg8t/Dk2PaVsOkM2Ck4ELYeVcP5A==,iv:X5XP6EV6isOQsWNsxRW6rS8tC1lrT8wxpvAJlB9XU7M=,tag:BKVi14qdhxd/RTP2ha/Dxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRlFrbDdIZVhCVU5SeUgr
            S2RVUzR2VmtZeDhsZldhQWhITHgrZUpEV0R3Ck93eUl6UnBwcmJZNkh0OTdkK3NS
            bWFBT3IvL1dhVXAxRWpNUzJJSUQzVTgKLS0tIFVJWWNPRDNyblZsUDRvVXR2R3Vh
            bXUveU5YZjJtVjZKbVQ2OWVZL2oyRTQKq8pf0KFz+rzhoZw2gpvyLp1TobP8RcWU
            Ygw1pF5TDJ2WiSAgaTpQsegLL+TpMAFDq57Te2mSB61BeStMLFR4dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zeu46ksgr0upauaf4dd7ftftvxzxz4n32j8k89m484rezq575q2sqkdpsz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbGo2eHpYUTIxWmpnWnpX
            QWJDeXNsSDYxNURDOS8xUmV2ek4vR0NpU1dNCmNHOWVFaXJZZWRjUmFSSUU2a1Jk
            MjJtUkFQYUhkUU56bjZOMFFHVGtsbVUKLS0tIHhyUG5GWVN2TllXMklLamNzejU1
            b3BMdTN4ZUxaa2NyWWMwMWQwQnhZYTQKGdiNV82MzHItXk3IAMnm0oRIecY83UcI
            IUMvaVZW/J81kQoe7MSeesRFi6GMK95SJAwkcLu8AS7ZMXs2tl/qsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHNYVTJ3ZyBBbWp6cE1k
            LzNEdnBMekV2T0U4a2tiYWp6Tk15MVVxMDNRVkNNZEdjcUtXQgo2Z2Y0SEF3Z0RP
            Nm9xL3VMNzVuYW5yaVNCS1VtSm1JTWtzeFUyV0g0Z1RjCi0tLSAvN1RRdUR6c1p0
            Q1djUk1kMWtsUlROTi9Malp3UU10YnBXVlg5SlE1UTlJCt14WVJHQCLas5hHXEtx
            S4s3wwVPmtisbfZQwXWGhfXoaApZCV4VTtOPAYy0Y2nn2n0VXsu/4duQPoMCwUxH
            T6M=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2agt4tz997s7q79vthfvu7gnd0yjmhgvvl7hmeqw8g8nd7fcxafxpr0vh6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T18:48:44Z"
    mac: ENC[AES256_GCM,data:6CET9IswTTXvLYdnlEviYZXZEG1OyIUSxvtwErRCpyb7PufJnVfR+Cjma+3bj2SlmlY0INBtlbSF+eJdL+qfpoXyKU8r4k1SUKlBpLAcDTPaUn3zhK4Uab82Z9XwE0441Ixntw48T433YD2EsLTVgF7YXBwe5iEqQu5pkUZYnxo=,iv:i5/WW+GHgTwUeqEi0o99YSon2vZMtgXVe2/578DOsFg=,tag:ZTt/iFhj8Ag448C80UjBYg==,type:str]
    version: 3.13.2
