package:
  name: zfs-exporter
  version: 2.4.1
  epoch: 0
  description: ZFS metrics exporter for Prometheus
  target-architecture:
    - x86_64
  copyright:
    - license: MIT

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/v3.24/main
    packages:
      - bash
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/pdf/zfs_exporter/releases/download/v${{package.version}}/zfs_exporter-${{package.version}}.linux-amd64.tar.gz
      expected-sha256: d384ae8f5efdcf6e4e288933acb5336bf3d14c6a422f161756c9a321d20be945
      delete: true
      strip-components: 1

  - runs: |
      install -Dm755 zfs_exporter "${{targets.destdir}}/usr/bin/zfs_exporter"
