---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: intel-device-plugins
  namespace: node-feature-discovery
spec:
  interval: 30m
  url: https://github.com/intel/intel-device-plugins-for-kubernetes
  ref:
    tag: v0.32.1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-node-feature-rules
  namespace: node-feature-discovery
spec:
  dependsOn:
    - name: node-feature-discovery
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins
  path: /deployments/nfd/overlays/node-feature-rules
  prune: true
  timeout: 10m
