---
apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 30m
  url: https://github.com/kubernetes-sigs/node-feature-discovery
  ref:
    tag: v0.17.4
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: node-feature-discovery
  path: /deployment/overlays/default
  prune: true
  timeout: 10m
  deletionPolicy: WaitForTermination
