---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebooks
  labels:
    sshfs-volume: ebooks
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      sshfs-volume: ebooks
  template:
    metadata:
      labels:
        sshfs-volume: ebooks
    spec:
      automountServiceAccountToken: false
      hostUsers: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: sshfs
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - SYS_CHROOT
                - SETGID
                - SETUID
                - DAC_OVERRIDE
            readOnlyRootFilesystem: true
          image: ghcr.io/michaelbeaumont/sshfs-server:latest
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: ssh
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: ssh
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: authorized-keys
              mountPath: /root/.ssh/authorized_keys
              subPath: authorized_keys
            - name: authorized-keys
              mountPath: /home/user/.ssh/authorized_keys
              subPath: authorized_keys
            - name: host-keys
              mountPath: /etc/ssh/ssh_host_ed25519_key
              subPath: ssh_host_ed25519_key
            - name: host-keys
              mountPath: /etc/ssh/ssh_host_ed25519_key.pub
              subPath: ssh_host_ed25519_key.pub
            - mountPath: /etc/ssh/sshd_config.d/sshfs.conf
              name: sshd-config
              subPath: sshfs.conf
            - mountPath: /mnt
              name: ebooks
          resources: {}
      volumes:
        - name: authorized-keys
          configMap:
            name: authorized-keys
            defaultMode: 0444
        - name: host-keys
          secret:
            secretName: host-keys
            defaultMode: 0400
        - name: sshd-config
          configMap:
            name: sshd-config
        - name: ebooks
          persistentVolumeClaim:
            claimName: ebooks
---
apiVersion: v1
kind: Service
metadata:
  name: ebooks
spec:
  selector:
    sshfs-volume: ebooks
  ports:
    - port: 22
      targetPort: ssh
      name: ssh
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: ebooks
  labels:
    external-dns: "true"
spec:
  parentRefs:
    - name: services
      namespace: infra
      sectionName: sshfs
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: ebooks
          port: 22
---
apiVersion: zfs.openebs.io/v1
kind: ZFSVolume
metadata:
  name: ebooks
  namespace: openebs
  finalizers:
    - k8rn/dummy-finalizer
spec:
  capacity: "3985729650688"
  fsType: zfs
  ownerNodeID: k8rn-core
  poolName: data
  volumeType: DATASET
  shared: "yes"
status:
  state: Ready
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sshfs-ebooks
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    name: ebooks
  csi:
    driver: zfs.csi.openebs.io
    fsType: zfs
    volumeAttributes:
      openebs.io/poolname: data
    volumeHandle: ebooks
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8rn-core
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-zfs-data
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebooks
spec:
  volumeName: sshfs-ebooks
  storageClassName: openebs-zfs-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ebooks-backup-local
spec:
  sourcePVC: ebooks
  trigger:
    schedule: "30 0 * * *"
  restic:
    pruneIntervalDays: 14
    moverSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    repository: restic-config-ebooks-local
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Snapshot
    storageClassName: openebs-zfs-data-delete
    cacheStorageClassName: openebs-single-replica-delete
    cacheCapacity: 5Gi
    volumeSnapshotClassName: openebs-zfs-localpv-delete
    moverVolumes:
      - mountPath: local-backups
        volumeSource:
          persistentVolumeClaim:
            claimName: ebooks-backup-local
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sshfs-ebooks-backup-local
spec:
  capacity:
    storage: 1Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: ebooks-backup-local
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/mnt/backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8rn-core
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebooks-backup-local
spec:
  volumeName: sshfs-ebooks-backup-local
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
