apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
labels:
  - includeTemplates: true
    includeSelectors: true
    pairs:
      app.kubernetes.io/name: linkding
patches:
  - patch: |-
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: links
      spec:
        hostnames:
          - links.${services_hostname_suffix}
resources:
  - linkding.yaml
  - pvc-data.yaml
  - restic-secret.yaml
  - networkpolicy.yaml
  - oidc.yaml
