apiVersion: v1
kind: ConfigMap
metadata:
    name: oidc-config
data:
    LD_ENABLE_OIDC: ENC[AES256_GCM,data:FP7f/Q==,iv:aIRCgucvLWkXkO49llT6jFQv5OjXxVlWfws0gXWdpS0=,tag:BgskF5r9EbZ5TCjAbEBxoQ==,type:str]
    LD_DISABLE_LOGIN_FORM: ENC[AES256_GCM,data:0R0Sag==,iv:DqonV61xjIrG4cEW6RJnqbDJ7ni1D8rILgFlsaIPW8s=,tag:kJlnrimMEtXmdnw9GtUMZA==,type:str]
    OIDC_OP_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:aX86yb16hZ7ML81u3j/so+SxJtaELAh/un862NL8g2t39eOu4Q==,iv:cBywVFozYxr+5DYB1hxNKZ4g0Zf6Yn3wqqRqbStpixg=,tag:jv8y3oCbA6CzGELauVwcTA==,type:str]
    OIDC_OP_TOKEN_ENDPOINT: ENC[AES256_GCM,data:+AC3dlyc/RueEfyqfMXV1KH3PDGDDCI/iDdKCe5lmaegX0sGEhwWIr42,iv:2Bd568VSMDNdXOtyZtZhhUUmpjYcQpVCGtVyIje9mUM=,tag:CH0wYeoAwYiE5mokw2aG5g==,type:str]
    OIDC_OP_USER_ENDPOINT: ENC[AES256_GCM,data:Ml3f2aqJIuThxVQrlA/BHMQeXDQk/BIn5daZrHCMYMnRdHH9Ol7JBcgNaydO,iv:2nwclPWDjv7KlRd8MYAJbPBLJX8QYAjxo9nqHH24h6w=,tag:wZytInuL3WBDj8geQrOHMw==,type:str]
    OIDC_OP_JWKS_ENDPOINT: ENC[AES256_GCM,data:pJG8FvxfmpIpbcPfXbhovu4NjQEbS3yKsKrW8CmnFlJSGXxM6svrhKAiT7BHvW9qCQ==,iv:fAqocVWHNAtz3AF+niqG2o0cWKrlIHHdID+46tYofzk=,tag:k0aByt+bm2PXlSocmDZ5yQ==,type:str]
    OIDC_VERIFY_SSL: ENC[AES256_GCM,data:DZ1P7A==,iv:fsCg961pCqTCZaU/kENwYkcV29pDZLbRBanPMAKBfmo=,tag:Kkr8Mf9MM0OCAOsHA0B6mA==,type:str]
    OIDC_USE_PKCE: ENC[AES256_GCM,data:aKKcxA==,iv:QJOa5SBaNTCM0U20HQ0KVyuPurjDWOdzTdF72kuGDWQ=,tag:7VGfEJzfeOPprPXtrjJlHA==,type:str]
    OIDC_USERNAME_CLAIM: ENC[AES256_GCM,data:l69AhYfSuDoTO2N46ZgkRrQg,iv:wBYuCEr0IA7d9t6eLsfL7L7HX0CiDdV1eGzxtJkYeGU=,tag:AED/iP1lkDtdECAc+Ilzdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVnpaaEt4QkhIVTN1VFlj
            K2tKOFE3Z1BzRlN1Slk3cnFzSEVnang2cldFCnhLNnliK01CWng0bXRmNTY2Um0z
            MEVnbDQ1aHU0UHV0Y3ozOGtEUXZLaGMKLS0tIERoTXdkZE95R1lES0Irbkd0SlBu
            eDhuNm4xUWRFNGdMOVp3RHlDektWRFkKAQNfDYN5Q34J6czrIzHGQpvdEFPBTYFk
            M6wjDO6ON99lqVwFoRBMI8hArgx+ZzlP69Ypf9/PasbNvHcZOzUM1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zeu46ksgr0upauaf4dd7ftftvxzxz4n32j8k89m484rezq575q2sqkdpsz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WEZQdHB6WTkwcUNUU0NJ
            ZzNySDRUQmhqYVp3bkN6L3IreTdEMkc5eFdrCmdnT0RPOHpWdjB0dEhzSmpRcTBS
            bkZWTUJjR3RZc0pmL1dTMmkxS3FyczQKLS0tIC8wWERndjZqL2ZHUWh4NWxnQU5q
            b1NGM2N3dnBJOCthcHAzN28wRnAyUTAKMDxNfCR4yHo22SLwX/UyfDCZQnHiC5Qi
            yO0qL9Pvq7AEwjEyTNeoynuhtYiND8dongQtOh68kBfBmhwfC0eAww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHNYVTJ3ZyBBNG1DdTJV
            R2JlNk9kaTZ4OGxNbkEvcXk0SEI0d09TTllqVk9vQ2hIM0NnaQowNWtkRTJJUkZL
            alZhUHhORVVWc3JaSlp3Y3pZK1RPTUV0Rms3WEsxTjNnCi0tLSA0RTByemtNQ2tj
            M2lFTkliUkE2WTA3cGlGWEluZVJUWkI2TVZJemtYYk1JCg6gVB8lulJ7nsCIjZLB
            QrbGpeT1zGpb66ndIJbGzpDYSwlKPdS84M/2PA8cEVViPOLweM3Zz3cEwyxyMmAX
            BjQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2agt4tz997s7q79vthfvu7gnd0yjmhgvvl7hmeqw8g8nd7fcxafxpr0vh6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-28T18:49:04Z"
    mac: ENC[AES256_GCM,data:nVk0XrZWzSh/lBXMDuu77EGNnmjR9iRQAL6POgqUD6+zSTYgGxOy60X0w+nZrLv+fN+uO2VBuSRi0sRHYEF6vLtY2wCRBhkfKrM7HCgb/ZhI+x1arvddO855NlE6WIV5SiS7E8xSSe27Xw/MbIePG7lQBtQtQsYOpkEraqeBBO0=,iv:oJCMgAGaUL+b9RrWXfXLZtmy8OCoIdUEK43D2IshRKI=,tag:L9Ft+5terEq9/gR8lfXNCA==,type:str]
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: oidc-client
type: Opaque
stringData:
    OIDC_RP_CLIENT_ID: ENC[AES256_GCM,data:ZzaTs8BGbHHJ+38sAHnieR7QyIgoib5NFyrP4eNGLqkwgMnw,iv:qswez9P1fHK5HaLseUXJnGhmee/wQ8104REejfcm3G0=,tag:7d2atDOcK2Wrp5np9r+/mA==,type:str]
    OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:Yaw4zCTNHrlmYYWk9yvZjj+H116VHUzMDx96YpIGgPU=,iv:CWpNzWDE3uHrrelmnfWOUQ05FWiXMun4+qe7cdwObPU=,tag:Y6qFMnKz/aG0/+PkVIBcSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVnpaaEt4QkhIVTN1VFlj
            K2tKOFE3Z1BzRlN1Slk3cnFzSEVnang2cldFCnhLNnliK01CWng0bXRmNTY2Um0z
            MEVnbDQ1aHU0UHV0Y3ozOGtEUXZLaGMKLS0tIERoTXdkZE95R1lES0Irbkd0SlBu
            eDhuNm4xUWRFNGdMOVp3RHlDektWRFkKAQNfDYN5Q34J6czrIzHGQpvdEFPBTYFk
            M6wjDO6ON99lqVwFoRBMI8hArgx+ZzlP69Ypf9/PasbNvHcZOzUM1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zeu46ksgr0upauaf4dd7ftftvxzxz4n32j8k89m484rezq575q2sqkdpsz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WEZQdHB6WTkwcUNUU0NJ
            ZzNySDRUQmhqYVp3bkN6L3IreTdEMkc5eFdrCmdnT0RPOHpWdjB0dEhzSmpRcTBS
            bkZWTUJjR3RZc0pmL1dTMmkxS3FyczQKLS0tIC8wWERndjZqL2ZHUWh4NWxnQU5q
            b1NGM2N3dnBJOCthcHAzN28wRnAyUTAKMDxNfCR4yHo22SLwX/UyfDCZQnHiC5Qi
            yO0qL9Pvq7AEwjEyTNeoynuhtYiND8dongQtOh68kBfBmhwfC0eAww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHNYVTJ3ZyBBNG1DdTJV
            R2JlNk9kaTZ4OGxNbkEvcXk0SEI0d09TTllqVk9vQ2hIM0NnaQowNWtkRTJJUkZL
            alZhUHhORVVWc3JaSlp3Y3pZK1RPTUV0Rms3WEsxTjNnCi0tLSA0RTByemtNQ2tj
            M2lFTkliUkE2WTA3cGlGWEluZVJUWkI2TVZJemtYYk1JCg6gVB8lulJ7nsCIjZLB
            QrbGpeT1zGpb66ndIJbGzpDYSwlKPdS84M/2PA8cEVViPOLweM3Zz3cEwyxyMmAX
            BjQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2agt4tz997s7q79vthfvu7gnd0yjmhgvvl7hmeqw8g8nd7fcxafxpr0vh6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-28T18:49:04Z"
    mac: ENC[AES256_GCM,data:nVk0XrZWzSh/lBXMDuu77EGNnmjR9iRQAL6POgqUD6+zSTYgGxOy60X0w+nZrLv+fN+uO2VBuSRi0sRHYEF6vLtY2wCRBhkfKrM7HCgb/ZhI+x1arvddO855NlE6WIV5SiS7E8xSSe27Xw/MbIePG7lQBtQtQsYOpkEraqeBBO0=,iv:oJCMgAGaUL+b9RrWXfXLZtmy8OCoIdUEK43D2IshRKI=,tag:L9Ft+5terEq9/gR8lfXNCA==,type:str]
    version: 3.11.0
