---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - ImageVolume
        - GPUsWithDRA
    imagePullPolicy: IfNotPresent
    seccompConfiguration:
      # Make sure PodSecurity admits the Pods
      virtualMachineInstanceProfile:
        customProfile:
          runtimeDefaultProfile: true
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
  # Node affinity prevents more than one from running anyway
  # and this effectively disables the PDB
  infra:
    replicas: 1
