---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: syncthing
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-sync-apps
    namespace: flux-system
  path: ./k8s/manifests/apps/syncthing
  prune: true
  timeout: 10m
  deletionPolicy: WaitForTermination
  decryption:
    provider: sops
    secretRef:
      name: sops
  postBuild:
    substitute:
      services_hostname_suffix: "${services_hostname_suffix}"
