apiVersion: v1
kind: Secret
metadata:
    name: immich-database-app
stringData:
    username: ENC[AES256_GCM,data:tx1600LA,iv:iUwQVFmA35LevszTM/sZ9VDoCPDjxnyw1Rr7SjYfII8=,tag:OO/Gb2PD6zR+i6pxIAu/lQ==,type:str]
    password: ENC[AES256_GCM,data:cpaST/6gaiULRwry6z2ljJtt,iv:Eu3i/SS/mbW6jQI8eg723zHgIcPBHugXc44yGiyn8UI=,tag:lmUNl/XBNr8iWo401FSb7w==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeW52ZE1HeXptU1Q0aGZX
            czIzR29ralcwc2Nldzh6WURnYzFha0ZJR2tnCkxpendKeW1TNTNmNkRhbmFCaDJu
            SFpMQmpBakEya0JTZmxxa1BuQlIrYmMKLS0tIDhCRmtuSlR0Q3BOamptakpUU0Q1
            eG00c3FCL2Z6bFRZNFh5K1dCbXA2c1EKZxKknASEe4bbt1ArE7Rzlq1ij5+WXI3z
            6Hjl2DVTCMSi3jlSb2NWTf0NW3J3KXt0aRPg5Q65Wp/yH3KPbnOgoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zeu46ksgr0upauaf4dd7ftftvxzxz4n32j8k89m484rezq575q2sqkdpsz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlblVBUlorU05pbFNMd0E1
            Um42R1hCOXFLcDRZZWZGUS80VDN1OWNxb0ZnCmppYU1KMTJBcWNoOVhFZE1ZVnBy
            Z09zK0xqMEF2RmpUQi9JY1BGTjlBYTgKLS0tIFVRWjF0Zmh2SkY3MDZRRWZnUzdN
            OUk3K0phNXY2TnlOcER4cnluazdTYUEKhN2JGyXua3F6x4AOKvYuNU3ZOBKHKNg6
            gk4LBmcFPr1Yuh6M6e5OBybaYS+Q+YHpiWRE28Ku83p3svLgB0eOYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHNYVTJ3ZyBBOE96Uys3
            OWNVS2kwNTM1K0twbG1yaHNTcWZEcTdpbU1ubDB0emdmci94RgovOW5YQUxlNkYw
            aTNQazUwR1d5N215eEJhNXNyb0tUdDNsbDVWZXpYeTkwCi0tLSBnNnJ0NHFnMmR0
            K0ZtQmdtemRzbEhqMWZxL1BpZk5TRUc5V2xYUjRlWkxFCrkdX+rx8jSt/3ZUnhAa
            ZxYqTRx2Gvqnr1xbMQLiyYULGXYscRPBr/atwFH/iaqZkbsTsM2uet5fML3b0bgx
            Yxk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2agt4tz997s7q79vthfvu7gnd0yjmhgvvl7hmeqw8g8nd7fcxafxpr0vh6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-28T18:49:04Z"
    mac: ENC[AES256_GCM,data:1V1h+5RjGw5RxnFFD2KrlzXolzsY9ycrAb1XrfY0gUREuMb44nlFC5c9BNXbkRyEggsyCuOjeGNgEYNCsohaTDxvVJLy7yigHM8hwGKSxVNOeMnU5nzcZCcEUKUXHcIJOc4Vs/T7+/2rtI8W++L3y7iWeC4iX7L/CFMGbco0K54=,iv:6sgj162lcNAK3zfadsa9jpS5f21TmlKbTn6TaNt9hYU=,tag:vmKGWe8Hg+FCkKBE78CsVw==,type:str]
    version: 3.11.0
