apiVersion: v1
kind: Secret
metadata:
    name: immich-database-app
stringData:
    username: ENC[AES256_GCM,data:tx1600LA,iv:iUwQVFmA35LevszTM/sZ9VDoCPDjxnyw1Rr7SjYfII8=,tag:OO/Gb2PD6zR+i6pxIAu/lQ==,type:str]
    password: ENC[AES256_GCM,data:cpaST/6gaiULRwry6z2ljJtt,iv:Eu3i/SS/mbW6jQI8eg723zHgIcPBHugXc44yGiyn8UI=,tag:lmUNl/XBNr8iWo401FSb7w==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWmFhNWJPMEswdmI4RHlo
            L1J6RmN1VVhTTFZRdE9pTDdEWGpLZW1uYUhjCjhjWGZsNDdoVDJkUmpwN1BTeHF1
            ZjFSSFdrVktSNXVyOExIQUFzcVVTTDAKLS0tIFpVcHVDUkt3OTRodHg5T1oyWkJu
            Yk0wSm5LdmN4ajFEQ1hlMVB4d2orckUK+AH8YCb7ar3inbqqziwOhTsnILrADZtF
            l/fEj8MZDIgNW5/bAh7z6ikNXwL7RiKuUXQ5wBJdDxA91zb9UH9MSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:49:04Z"
    mac: ENC[AES256_GCM,data:1V1h+5RjGw5RxnFFD2KrlzXolzsY9ycrAb1XrfY0gUREuMb44nlFC5c9BNXbkRyEggsyCuOjeGNgEYNCsohaTDxvVJLy7yigHM8hwGKSxVNOeMnU5nzcZCcEUKUXHcIJOc4Vs/T7+/2rtI8W++L3y7iWeC4iX7L/CFMGbco0K54=,iv:6sgj162lcNAK3zfadsa9jpS5f21TmlKbTn6TaNt9hYU=,tag:vmKGWe8Hg+FCkKBE78CsVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
