---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeTemplates: true
    includeSelectors: true
    pairs:
      app.kubernetes.io/name: immich
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: immich
      namespace: immich
    unsetOnly: true
    fieldSpecs:
      - path: spec/claimRef/namespace
        kind: PersistentVolume
        name: immich-photos
        create: true
patches:
  - patch: |-
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      metadata:
        name: immich-server
      spec:
        hostnames:
          - photos.${services_hostname_suffix}
resources:
  - database.yaml
  - database-secret.yaml
  - photos.yaml
  - restic.yaml
  - server.yaml
  - machine-learning.yaml
  - valkey.yaml
