apiVersion: v1
kind: Namespace
metadata:
    name: external-dns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mc6573986ak84qcs9slsel3rahaw8gjseh5f085gyr6zhz6yuu7qqhluwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSUxzblZ6eW9IQmZJYnBO
            VG9CeDd5Y0RvcDJHc3V4RTd5aEdpbUo5aGo4Cmh5RE1GTzJockRtK0s4OXFOSkVh
            S1cyWkZCUDR2WVMyMDVEMTI5SmUwNzgKLS0tIGpreklmZ1ZMYkN2enA5S0FvMXVG
            UTFPSEZVTzVseHhCQ2EwUFppUWVDaEkKImc0+qoBPzDQqAE21AXjwvTMaRalFGrz
            oxC540vkyttoiA/SB4wQe7r3YombgGncaN3cFJuEs9LouMHr0LZaig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T02:34:09Z"
    mac: ENC[AES256_GCM,data:IgCF1mOK5UZlgfkwyP2dzONf2MwTGWGunDovBSRo2fQ/piYFTftKo1ChDsvq7XQtBaxkgvsiwS6N0n0In1jL2ra9Vp8IxI0fMUAwwKWUOTLGxypQT/CWJU+ci9UscDHtM1EpoJt0bn3xRYF4Tw6lq0uDVSL9Vq4pKqHdsfIdBKU=,iv:bDLDzV8lttLXvJPNPDUDd+Bsdtmoq8zuluhWnEtsf/k=,tag:uHSB6tjtnlHVaP2khOphjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: external-dns
    namespace: external-dns
spec:
    interval: 10m0s
    url: https://kubernetes-sigs.github.io/external-dns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mc6573986ak84qcs9slsel3rahaw8gjseh5f085gyr6zhz6yuu7qqhluwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSUxzblZ6eW9IQmZJYnBO
            VG9CeDd5Y0RvcDJHc3V4RTd5aEdpbUo5aGo4Cmh5RE1GTzJockRtK0s4OXFOSkVh
            S1cyWkZCUDR2WVMyMDVEMTI5SmUwNzgKLS0tIGpreklmZ1ZMYkN2enA5S0FvMXVG
            UTFPSEZVTzVseHhCQ2EwUFppUWVDaEkKImc0+qoBPzDQqAE21AXjwvTMaRalFGrz
            oxC540vkyttoiA/SB4wQe7r3YombgGncaN3cFJuEs9LouMHr0LZaig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T02:34:09Z"
    mac: ENC[AES256_GCM,data:IgCF1mOK5UZlgfkwyP2dzONf2MwTGWGunDovBSRo2fQ/piYFTftKo1ChDsvq7XQtBaxkgvsiwS6N0n0In1jL2ra9Vp8IxI0fMUAwwKWUOTLGxypQT/CWJU+ci9UscDHtM1EpoJt0bn3xRYF4Tw6lq0uDVSL9Vq4pKqHdsfIdBKU=,iv:bDLDzV8lttLXvJPNPDUDd+Bsdtmoq8zuluhWnEtsf/k=,tag:uHSB6tjtnlHVaP2khOphjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: external-dns
    namespace: external-dns
spec:
    install:
        crds: CreateReplace
    upgrade:
        crds: CreateReplace
    interval: 10m0s
    targetNamespace: external-dns
    chart:
        spec:
            chart: external-dns
            sourceRef:
                kind: HelmRepository
                name: external-dns
    values:
        policy: sync
        txtOwnerId: k8rn
        sources:
            - gateway-httproute
            - service
        provider: cloudflare
        extraArgs:
            - --label-filter=external-dns==true
            - --managed-record-types=A
            - --managed-record-types=AAAA
        env:
            - name: CF_API_TOKEN
              value: file:/cloudflare/token
        secretConfiguration:
            enabled: true
            mountPath: /cloudflare
            data:
                token: ENC[AES256_GCM,data:w4WAIxeQJ/Felpb+plnsjzWmtXxvjD3Ee9t9DogexEix6xMij58Lew==,iv:U0jFxKYfATMkjHIIN+y9p6cWPb2t3dofzn2BTd1709s=,tag:Ix/kZTtEOeVNsJcMQvowJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mc6573986ak84qcs9slsel3rahaw8gjseh5f085gyr6zhz6yuu7qqhluwx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSUxzblZ6eW9IQmZJYnBO
            VG9CeDd5Y0RvcDJHc3V4RTd5aEdpbUo5aGo4Cmh5RE1GTzJockRtK0s4OXFOSkVh
            S1cyWkZCUDR2WVMyMDVEMTI5SmUwNzgKLS0tIGpreklmZ1ZMYkN2enA5S0FvMXVG
            UTFPSEZVTzVseHhCQ2EwUFppUWVDaEkKImc0+qoBPzDQqAE21AXjwvTMaRalFGrz
            oxC540vkyttoiA/SB4wQe7r3YombgGncaN3cFJuEs9LouMHr0LZaig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-09T02:34:09Z"
    mac: ENC[AES256_GCM,data:IgCF1mOK5UZlgfkwyP2dzONf2MwTGWGunDovBSRo2fQ/piYFTftKo1ChDsvq7XQtBaxkgvsiwS6N0n0In1jL2ra9Vp8IxI0fMUAwwKWUOTLGxypQT/CWJU+ci9UscDHtM1EpoJt0bn3xRYF4Tw6lq0uDVSL9Vq4pKqHdsfIdBKU=,iv:bDLDzV8lttLXvJPNPDUDd+Bsdtmoq8zuluhWnEtsf/k=,tag:uHSB6tjtnlHVaP2khOphjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
