apiVersion: v1
kind: Secret
metadata:
    name: oidc-client-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:FoE1/iLplMcWFEuvaRTq+AYQxCf4IzQUpmYeDi34DjY=,iv:PKIoN4CbVN3msGeRhN0U7x1X/Kd/o3ttHwo3ZnCjSuA=,tag:UFVNJtThZMXg4Tcs8bi+3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUWxueVNBb0k3L3RYWnpN
            MUN4ejNwL0FLZWhuOFZVM3JWMi9FeTRUQVNFCkY5RUdDcW00WnRFSVlKdW5wajE2
            cXZGb1NMSHdDRkFpemw5a0NUNEk5Rk0KLS0tIE1qdFZNVkM0cFkyZTN4VXBiM3Q1
            NUZHUHZMZ09EcU51OVVqSjF3ZUFGOGsKG6jAeWi1LIl7+dr2CKO2IFCwiibrcBg0
            1pOtYfEyqS/bXCmjhc3xf8Upk684muByN6ZbejqqmXD+YesbZQny8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zeu46ksgr0upauaf4dd7ftftvxzxz4n32j8k89m484rezq575q2sqkdpsz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbDJjRm43TnI4MkZ1ZGJ0
            QVM3YWlLUnFkNHE4cE10cUJ1N3JRY0M5eXhFCnZORzl6UUxieTI0K2JJbVk3WEpo
            YzlZS3g0U3lQcGJ6d2wyYWFLMEo0dUUKLS0tIDFkaGhIZFlCaHRHY1A2TGFObUJC
            M3hMbnQ1NHA2VTdCM090aGhRSTVpMk0KgX4kyci+0EE9bbBgOmG64cNRUkxpcsv1
            oqeW9xukdY01fmXYSy0nMuuWyHjOmT9FxMmuC4D9UKb+dsydwbMyPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHNYVTJ3ZyBBNmJHMk1Q
            NmJLTVFTb3lqUXY4KzI5bFkzem5aMnRyY1FDYXdWSER5S0M0WgptR0l5clFwUXFP
            djJaMzV4Vk5BWmhUbStFdGx6MXBRQ3NWYkdWVnVyczhBCi0tLSBaalNMd3RZVFlq
            L3BIbzFqQ3EwTzRXYVczUzlScmZwYTVYQXRBTGdkanJFCiEzl48n0cq07TwqkN5A
            gY2tCv7Sii1TymgZAoiqRwTRmFO2nTuDtB3Le5+3AAiRG0xDLszTJtxUoU4NkWii
            Q78=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q2agt4tz997s7q79vthfvu7gnd0yjmhgvvl7hmeqw8g8nd7fcxafxpr0vh6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T18:28:00Z"
    mac: ENC[AES256_GCM,data:cEhNZ2H/8PygTDqosH+f6gWRfxKIqLyFKSfULQK0uutDg1BHmw6YCD8dWje3iWk6PwXyDUXVxfuj7uXyqHbiFbQ9lEXOX8pfwBg/7xYURDSfqRmKbXzesFUs5RJSkSIMn3fv0LEj0rVg4YutzDvrUz2fFxkRg7aFX9STJsIkKy0=,iv:zFSB2sBi8rSsZJS7Sl70jFmkz5WEU8qYogF+dImNrzw=,tag:mJ0wrfKE9sfF/qvbvtZoHQ==,type:str]
    version: 3.13.1
