apiVersion: v1
kind: Secret
metadata:
    name: oidc-client-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:FoE1/iLplMcWFEuvaRTq+AYQxCf4IzQUpmYeDi34DjY=,iv:PKIoN4CbVN3msGeRhN0U7x1X/Kd/o3ttHwo3ZnCjSuA=,tag:UFVNJtThZMXg4Tcs8bi+3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c3VrblB3S1lKNlRiTzMr
            cWtUQk5VcFIxbEd4YzVvMktycHd4TUEybFFJCkx4ODdHTitQUmM4Y1Z5c0NYUTBR
            YzlHVjFBVXRzOWZYQythbU95RDZueEkKLS0tIG8wRS85SVN4ZndGS1JManl5cm5Q
            cjg4d01LM2VmekRKaVFCcFR6a0g5bEUKGsSogSHWu9WQM+mFE48/okNlQD5r2h1b
            BfZDkHDJM8whNiByiNtm9YS2gDz8j7nJH5DRK8nGSHL6iHDRevC3oA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T18:28:00Z"
    mac: ENC[AES256_GCM,data:cEhNZ2H/8PygTDqosH+f6gWRfxKIqLyFKSfULQK0uutDg1BHmw6YCD8dWje3iWk6PwXyDUXVxfuj7uXyqHbiFbQ9lEXOX8pfwBg/7xYURDSfqRmKbXzesFUs5RJSkSIMn3fv0LEj0rVg4YutzDvrUz2fFxkRg7aFX9STJsIkKy0=,iv:zFSB2sBi8rSsZJS7Sl70jFmkz5WEU8qYogF+dImNrzw=,tag:mJ0wrfKE9sfF/qvbvtZoHQ==,type:str]
    version: 3.13.1
