apiVersion: v1
kind: Secret
metadata:
    name: basic-auth
type: Opaque
stringData:
    credential: ENC[AES256_GCM,data:dqNO94GN0dsIlWDhUFAs0cce1GVjmjny1H8=,iv:DJzloxuQsRNSvGm2ZI4f1LSshjNS+Ivz4kgKwV/2+qc=,tag:GrdrN+u1FBgykCU5sHIoAA==,type:str]
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRkhDdnplM2hGNFpWb1F1
            TGYwSll1VFozV0N2OEpUd3kxN2NoWVpEcEdFCmRQYVN3NTZydUE0c2NOT3JnY2RW
            bm14bmFnWnJ3Wm5UY0h1V2p5TEhaV2MKLS0tIEQ1TzZwbzBuSm5tTm1Wcml4NlJi
            QTdLNVBjMjkzbml2alJjZmlYUm11bzQKQf1ebZVUQmw6Ns/akegZyDACt92m9S9R
            Y5ca2fLzRXFNYkFjSHIBXabDhICrz3eEBb9w3OhK3DpkaUr5c5d5kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:48:19Z"
    mac: ENC[AES256_GCM,data:oterg8DSqYZe+OuUNxpprFDYtA0QRoG2kW4ZC0qNEnmDEwBVlEK62dFlcocnZIOdOHIwA3UxvQQbJs976YGDMDz9cY0eJCqYbDM/On24Irn16s25S139jUevz+bPOTxgvH8R5Rbw7Sm9WOUSE1HWEjI4GVkc8BGvKO4ENoc15po=,iv:hBbd7gpip44IayklS4W74Qo1cG9KlcX5ofZyR/1ChwA=,tag:lo15n9ITUK1eKOs4Sf2cCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
