---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-single-replica
parameters:
  protocol: nvmf
  repl: "1"
  thin: "true"
  fsType: xfs
allowVolumeExpansion: true
provisioner: io.openebs.csi-mayastor
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-single-replica-delete
parameters:
  protocol: nvmf
  repl: "1"
  thin: "true"
  fsType: xfs
allowVolumeExpansion: true
provisioner: io.openebs.csi-mayastor
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-data-unmanaged
parameters:
  fstype: zfs
  poolname: data
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
