---
apiVersion: v1
kind: ConfigMap
metadata:
    name: config
data:
    OIDC_AUTH_ENABLED: "True"
    OIDC_SIGNUP_ENABLED: "True"
    OIDC_REQUIRES_EMAIL_VERIFICATION: "True"
    OIDC_AUTO_REDIRECT: "True"
    OIDC_USER_CLAIM: preferred_username
    OIDC_ADMIN_GROUP: admins
    ALLOW_PASSWORD_LOGIN: "False"
