---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: lets-encrypt-staging
spec:
    acme:
        email: "${lets_encrypt_email}"
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: lets-encrypt-staging-account-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cloudflare-token
                        key: token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: lets-encrypt-prod
spec:
    acme:
        email: "${lets_encrypt_email}"
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: lets-encrypt-prod-account-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cloudflare-token
                        key: token
