---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-ula
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.128/25
    # - fd4a:f9c7:76ae:1::/64 # TODO cluster isn't ipv6
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local-ula
  namespace: metallb-system
spec:
  ipAddressPools:
  - local-ula
  interfaces:
  - enp1s0
  - enp2s0

