apiVersion: v1
kind: Secret
metadata:
    name: restic-remote-base
    namespace: flux-system
type: Opaque
stringData:
    RESTIC_REPOSITORY_BASE: ENC[AES256_GCM,data:AlQ8KSCTyHnC36w91hPJImu7DHVIAHsn1bRjFlqN7BJIyt4pl4irfFpqGw==,iv:7YuJ+1RGYaIExKU3CmS7dg1HM1REyfB/d8s12HUPDNM=,tag:1vqJLPx3l6l14aqhKGJxdg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZBsWIbnUggD6t34SvpP/9xC96Vc+5XFBaA==,iv:Uzo3s7Mj6HHRxGWzd8COZQHlGhbJYLapF+VrrTrxxI4=,tag:LJFXh2eyo1Cp3bzfriDklQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:kAPYRfkQurxdoqfJpxLo4M0ulilOjDzc9sVX1EtXsA==,iv:1vuLjk0xupg0Hqnn2lQyfJV0PoCrv5GxJOPYFo3JKko=,tag:P0y8BVdradxs8uld1BGBZg==,type:str]
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Ri92UzJYbVZ2NWpZZWFC
            dFlpUjF6dWY0VUgrQ0RGR0JOc21WT2F4UVVzCnFzU1N1R25YSlExK0ZzNE5jd1lD
            MTh3ZitNMzVxNzZKeEMwMHk5WmFDN2MKLS0tIFg3U3VWRE1IaUhmNkNaQnJyUTJp
            NnU5ajNyY3lzOFJCS3VHeDdiUG1LeWsK9lOnwwLeR94FSUv6u4SLjXIDYVG2OdBQ
            JPoU25kr+SQXeHrmxJlQXkvN2CUx4OrOuiSwtamckqNXft04Bksp9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:DHwj1uTOz6XLvTaFIskmOhIyZFcNrX0P3z/MkvznBm62VDxwsufXpA0ZP7X2ewErfuqfZ965pOUYo3v+abTIX32paFiQKUCem/VopP8qGmXp/qrO/RA55e4qN4Hat6oOPE69yOCq1Lh+02TLMniHrTZ+KBvZCWSHj4hkLYJd/Bk=,iv:GItG38pxL5xVbjaDShrnv+KVz52uvMa/uNF2oUqv5c4=,tag:tpdnKEBXEy7kXzjJTOqZsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic-remote-zfs-data-base
    namespace: flux-system
type: Opaque
stringData:
    RESTIC_REPOSITORY_ZFS_DATA_BASE: ENC[AES256_GCM,data:MJ2zGJ57hk7Ldi+5dbnWHbT+w5cKZjNquqZ2rE/7sLKpjpCYlo6KNQeY1H7rXg8=,iv:JIdjETBPZbeKvhj/TOhFkM+lUJMMV9odnuScbeOUio8=,tag:zEMJ3GGRKnNsWb8jJ8Itvw==,type:str]
    AWS_ACCESS_KEY_ID_ZFS_DATA: ENC[AES256_GCM,data:hRSQY6M2/n0OFtrfrEzoxUtJF613IwRf7w==,iv:sizzRuSTEIq+7WR1xnhsudjNwdpNnpHCnITvM1r3bSY=,tag:QsUkJrVRCPHadc9M+p2n8A==,type:str]
    AWS_SECRET_ACCESS_KEY_ZFS_DATA: ENC[AES256_GCM,data:FvNqMFzTyUsre8J3jY0LFk48bBer+RpEoTWv7+NsBQ==,iv:m+31QM+EscvPLdK5NCo7O/+eOdUAaS9dVo9jwCJGUII=,tag:oKfq1S3XxoOgWU7QqeKSug==,type:str]
sops:
    age:
        - recipient: age1e09aexflt8pshjftfrvzenx7n0wux84wxxc2fdmu970yxz0jauzqyglyp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Ri92UzJYbVZ2NWpZZWFC
            dFlpUjF6dWY0VUgrQ0RGR0JOc21WT2F4UVVzCnFzU1N1R25YSlExK0ZzNE5jd1lD
            MTh3ZitNMzVxNzZKeEMwMHk5WmFDN2MKLS0tIFg3U3VWRE1IaUhmNkNaQnJyUTJp
            NnU5ajNyY3lzOFJCS3VHeDdiUG1LeWsK9lOnwwLeR94FSUv6u4SLjXIDYVG2OdBQ
            JPoU25kr+SQXeHrmxJlQXkvN2CUx4OrOuiSwtamckqNXft04Bksp9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T18:53:13Z"
    mac: ENC[AES256_GCM,data:DHwj1uTOz6XLvTaFIskmOhIyZFcNrX0P3z/MkvznBm62VDxwsufXpA0ZP7X2ewErfuqfZ965pOUYo3v+abTIX32paFiQKUCem/VopP8qGmXp/qrO/RA55e4qN4Hat6oOPE69yOCq1Lh+02TLMniHrTZ+KBvZCWSHj4hkLYJd/Bk=,iv:GItG38pxL5xVbjaDShrnv+KVz52uvMa/uNF2oUqv5c4=,tag:tpdnKEBXEy7kXzjJTOqZsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
